addons:
  apt:
    sources:
      - chef-stable-xenial
    packages:
      - chef-workstation

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chef-workstation/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/bin/chef exec delivery local all
