---
name: ci

'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Chef Delivery
        uses: actionshub/chef-delivery@main
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@main

  integration:
    needs: [mdl, yamllint, delivery]
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          - 'windows-2012R2'
          - 'windows-2016'
          - 'windows-2019'
        suite:
          - 'chef-infra-12'
          - 'chef-infra-latest'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
